name: memo_program
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.27.3'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.2
  flutter_heatmap_calendar: ^1.0.5
  provider: ^6.1.2
  flutter_markdown: ^0.7.6+1
  simple_heatmap_calendar: ^0.4.0
  table_calendar: ^3.0.9
#  heatmap_calendar: ^1.0.1
  window_manager: ^0.3.7
  file_picker: ^8.3.2
  path_provider: ^2.0.11
  flutter_slidable: 3.1.2
  photo_view: ^0.15.0
  flutter_svg_provider: ^1.0.0
  archive: ^4.0.2
  permission_handler: ^11.3.1
  dio: ^5.8.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/avatar.jpg
    - lib/assets/addition_fill.png
    - lib/assets/tag.png
    - lib/assets/pen.png
    - lib/assets/back.svg
    - lib/assets/photos.svg
    - lib/assets/backFile.png
    - lib/assets/equipment.svg
    - lib/assets/file_download_icon.svg
    - lib/assets/file_upload_icon.svg
    - lib/assets/floder_icon.svg
    - lib/assets/memo_placeholder.png
    - lib/assets/camera.svg
    - lib/assets/nomemo_placehoder.png
  fonts:
    - family: SourceHanSans
      fonts:
        - asset: lib/assets/fonts/SourceHanSansSC-Regular-2.otf
        - asset: lib/assets/fonts/SourceHanSansSC-Bold-2.otf
          weight: 700


